### ISSUE TITLE
[v1.8] New `searchCutoffMs` index settings

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#630]
Related to https://github.com/meilisearch/integration-guides/issues/299

### Explanation of the feature

Introduction of the new index setting named `searchCutoffMs`. Available via `/indexes/:uid:/settings` (`GET`, `PATCH`, `DELETE`) and `/indexes/:uid:/settings/search-cutoff-ms` (`GET`, `PUT`, `DELETE`)
Default value is `null`. Expects an int as value.

More info about the usage of this new feature: https://meilisearch.notion.site/Search-cutoff-usage-fb5e9a07a7624965a541d0a6f8eb37bc

### TODO

- [x] Ensure the library accepts the new field `searchCutoffMs` when calling the methods related to the `/indexes/:uid:/settings (GET, PATCH, DELETE)` which are `getSettings()`, `updateSettings()` and `resetSettings` 
- [x] Add new methods corresponding to the new routes
 - [x] `GET /indexes/:uid:/settings/search-cutoff-ms`: create `getSearchCutoffMs()`
 - [x] `PUT /indexes/:uid:/settings/search-cutoff-ms`: create `updateSearchCutoffMs()`
 - [x] `DELETE /indexes/:uid:/settings/search-cutoff-ms`: create `resetSearchCutoffMs()`
- [ ] Add tests for each of these additions

⚠️ Make PRs pointing to `bump-meilisearch-v1.8.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by brunoocasali** [comment]
Hey @curquiza what do you think about keeping only: `['7.4', '8.3']` ?

**Comment by curquiza** [comment]
@brunoocasali what do you mean? In the tests, so drop some PHP version?

Not sure this is the topic of this issue, but we could open another one so that the community can fix it
