### ISSUE TITLE
[v1.9] Hybrid search changes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#647]
Related to https://github.com/meilisearch/integration-guides/issues/301

### Explanation of the feature

- Breaking: `_vectors` no longer returned in documents (by default). Use `retrieveVectors` during the search to see it.
- Extension to the `_vectors` field in documents: in the `_vectors` field, `text` can be an object and accept `embeddings` and `regenerate` fields
  - `embeddings` is an array of embeddings, as `text` can be
  - `regenerate` is a boolean

Usage: https://meilisearch.notion.site/v1-9-AI-search-changes-e90d6803eca8417aa70a1ac5d0225697

### TODO

- [ ] Related to the breaking change:
  - [x] Ensure `_vectors` is not a mandatory field
  - [x] Add the new search parameter `retrieveVectors`
  - [x] Add the new parameter `retreiveVectors` to get documents (POST and GET route)
- [ ] in the `_vectors` field, `text` can also be an object and accept `embeddings` and `regenerate` fields
  - `embeddings` is an array of embeddings, as `text` can be
  - `regenerate` is a boolean
- [ ] Add tests and fix tests if necessary

⚠️ Make PRs pointing to `bump-meilisearch-v1.9.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by curquiza** [comment]
Closed by #649
