### ISSUE TITLE
[v1.10.0] Language settings & search parameter

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#660]
Related to https://github.com/meilisearch/integration-guides/issues/302

### Explanation of the feature

Changes
- new settings `localizedAttributes` and the sub-methods associated to it
- new search parameter `locales`

Usage: https://meilisearch.notion.site/v1-10-Language-settings-usage-26c5d98b553349d9abacbe7aff698e4e

### TODO

- [x] Add a new search parameter named `locales` to the `search` method
- [x] Ensure the `updateSettings` route can accept the new `localizedAttributes` setting
- [x] Create new methods `getLocalizedAttributes`, `updateLocalizedAttributes` and `resetLocalizedAttributes` corresponding to the sub settings `GET/PUT/DELETE` routes
- [x] Add tests

⚠️ Make PRs pointing to `bump-meilisearch-v1.10.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by curquiza** [comment]
Closed by #662 

Will be released once v1.10 of meilisearch is out
