### ISSUE TITLE
[v1.12.0] New settings: `facetSearch` & `prefixSearch`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#694]
Related to https://github.com/meilisearch/integration-guides/issues/307

### Explanation of the feature

- New index settings: `facetSearch`
- New index settings: `prefixSearch`

Usage: https://meilisearch.notion.site/API-usage-Settings-to-opt-out-indexing-features-fff4b06b651f8108ade3f858aeb16b14

### TODO

- [ ] Ensure the methods `getSettings()`, and `updateSettings` can accept the new settings fields: `facetSearch` & `prefixSearch`
- [ ] Add the new methods: `getFacetSearch()`, `updateFacetSearch()` and `resetFacetSearch()` calling the appropriate Meilisearch routes
- [ ] Add the new methods: `getPrefixSearch()`, `updatePrefixSearch()` and `resetPrefixSearch()` calling the appropriate Meilisearch routes
- [ ] Add tests

⚠️ Make PRs pointing to `bump-meilisearch-v1.12.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by Strift** [comment]
Closed by #702
