### ISSUE TITLE
[v1.12.0] New batch routes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#695]
Related to https://github.com/meilisearch/integration-guides/issues/307

### Explanation of the feature

- New `GET /batches` & `GET /batches/:uid` routes
- New field in `task` object: `batchUid`

Usage: https://meilisearch.notion.site/Enhance-visibility-on-batched-tasks-1194b06b651f810b8fe0fab5d72846a8?pvs=74

### TODO

👉 Check carefully the usage above to ensure your new methods and objects integrate all the functionnalities

- [ ] Create two new methods `getBatch()` and `getBatches()` triggering the appropriate new route (check out `getTask` and `getTasks` since the behavior will be pretty similar)
- [ ] A new `batch` object will probably be needed to be created.
- [ ] Ensure the `task` object can accept the `batchUid` field
- [ ] Add tests

⚠️ Make PRs pointing to `bump-meilisearch-v1.12.0` and NOT `main`. Please do 1 PR for all of these changes, and not several.

**Comment by Strift** [comment]
Closed by #699
